In [2]:
import numpy as np

In [8]:
grid = {{110, 5, 112, 113, 114}, {210, 211, 5, 213, 214}, {310, 311, 3, 313, 314}, {410, 411, 412, 5, 414}, {5, 1, 512, 3, 3}, {610, 4, 1, 613, 614}, {710, -1, -2, 713, 714}, {810, -1, -2, 1, 1}, {1, -1, -2, 2, 2}, {4, -1, 4, 4, 1014}}

In [9]:
print(np.matrix(grid))

[[ 110    0    0    0    0]
 [ 210    0    0  113  114]
 [ 310    0    0  213  214]
 [ 410    0  112  313  314]
 [   5    5    5    5  414]
 [ 610  211    3    3    3]
 [ 710  311  412  613  614]
 [ 810  411  512  713  714]
 [   1    1    1    1    1]
 [   4    4    4    4 1014]]
